### ISSUE TITLE
Bug: unexpected output when using an unknown property key in sdk.record.format.options 

### ISSUE THREAD

**Issue by alarbada** [ConduitIO/conduit-connector-sdk#216]
### Bug description

When specifying a property that doesn't exist in the passed record, conduit writes the whole record instead of erroring.

### Steps to reproduce

Running this pipeline configuration should be enough to reproduce the error:

```yaml
version: "2.2"
pipelines:
  - id: example-pipeline
    status: running
    name: "s3-to-file"
    connectors:
      - id: example
        type: source
        plugin: generator
        settings:
          rate: 1
          format.type: structured
          format.options.id: int
          format.options.name: string
          operations: create

      - id: file
        type: destination
        plugin: "file"
        settings:
          path: ./destination.txt
          sdk.record.format: template

          # This works as expected
          sdk.record.format.options: '
            {{ printf "%v" .Payload.After }}
          '

          # This makes the pipeline fail
          sdk.record.format.options: '
            {{ printif "%v" .Payload.After }}
          '

          # But this doesn't.
          sdk.record.format.options: '
            {{ printf "%v" .Payload.Afterrrr }}
          '
          
          # And it doesn't matter whether there was previous output written or
          # not, the whole record is still written:
          sdk.record.format.options: '
            {{ printf "%v" .Key }}
            {{ printf "%v" .SomePropThatDoesNotExist }}
          '

          # Not using yaml multilines, and the issue still happens
          sdk.record.format.options: '{{ printf "%v" .SomePropThatDoesNotExist }}'

```

### Version

v0.12.2 linux/amd64

**Comment by alarbada** [comment]
I have to note that because I was writing to a file, it was fairly easy to notice this behaviour. But if I was to write to another destination the errors (if any) would be much more difficult to track, since the destination doesn't output a warning or anything.

I don't know if this is really what we want, but at the very least there should a single warning (not per record, otherwise there could be many logs) telling me that there was an error executing the template.

I must note, that by default go templates do error when a property is not defined:
https://go.dev/play/p/2npYlakxMd3

**Comment by alarbada** [comment]
Hello @maha-hajja, I'm sorry to answer late. Yes it is still happening:

![Image](https://github.com/user-attachments/assets/2e052f4c-daa9-4f8e-8bab-978df0d5a0fd)

With this pipeline config file:

```yaml
version: "2.2"
pipelines:
  - id: example-pipeline
    status: running
    name: "generator-to-file"
    connectors:
      - id: example-source
        type: source
        plugin: "generator"
        settings:
          rate: 10
          recordCount: 100
          burst.generateTime: 1s
          burst.sleepTime: 1s
          format.type: raw
          # format.options.id: int
          # format.options.name: string
          # operations: create

      - id: example-destination
        type: destination
        plugin: "file"
        settings:
          path: "test.txt"
          sdk.record.format: template
          sdk.record.format.options: '
            {{ printf "%s" .Payload.Afterr }}
          '
```
